# Generated by Django 2.0.3 on 2019-12-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('White', 'White'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Crystal', 'Crystal'), ('Blue', 'Blue')], max_length=7)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large'), ('Topper', 'Topper')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Bells',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('White', 'White'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Crystal', 'Crystal')], max_length=7)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large'), ('Topper', 'Topper')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Bow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('White', 'White'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Blue', 'Blue')], max_length=6)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large'), ('Topper', 'Topper')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Bulb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('White', 'White'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Crystal', 'Crystal'), ('Blue', 'Blue')], max_length=7)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ChristmasGreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greenChoice', models.IntegerField(choices=[(0, 'Balsam Fir'), (1, 'Fraser Fir'), (2, 'Canaan Fir'), (3, 'Douglas Fir'), (4, 'Grand Fir'), (5, 'Noble Fir'), (6, 'Concolor Fir'), (7, 'White Pine'), (8, 'Scotch Pine'), (9, 'Virginia Pine'), (10, 'Blue Spruce'), (11, 'Norway Spruce'), (12, 'White Spruce'), (13, 'Arizona Cypress'), (14, 'Leyland Cypress'), (15, 'Red Cedar'), (16, 'Holly')], default=0)),
                ('item', models.CharField(choices=[('Tree', 'Tree'), ('Wreath', 'Wreath'), ('Garland', 'Garland'), ('Centerpiece', 'Centerpiece'), ('Minitree', 'Minitree')], max_length=15)),
                ('smallAvail', models.BooleanField(default=True)),
                ('largeAvail', models.BooleanField(default=True)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Lights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('White', 'White'), ('Multi', 'Multi'), ('Blue', 'Blue')], max_length=5)),
                ('size', models.CharField(choices=[('25 lights', '25 lights'), ('50 lights', '50 lights'), ('100 lights', '100 lights'), ('250 lights', '250 lights'), ('500 lights', '500 lights')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ribbon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('White', 'White'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Crystal', 'Crystal'), ('Blue', 'Blue')], max_length=7)),
                ('size', models.CharField(choices=[('5 ft', '5 ft'), ('15 ft', '15 ft'), ('30 ft', '30 ft')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Crystal', 'Crystal')], max_length=7)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large'), ('Topper', 'Topper')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='TableRunner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('White', 'White'), ('Trees', 'Trees'), ('Bells', 'Bells'), ('Wreaths', 'Wreaths'), ('Bows', 'Bows'), ('Candy Canes', 'Candy Canes'), ('Snowflakes', 'Snowflakes'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=11)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='TreeStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Metal', 'Metal'), ('Plastic', 'Plastic')], max_length=6)),
                ('avail', models.BooleanField()),
                ('incInSpecial', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
