# Generated by Django 2.0.3 on 2019-12-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treestand',
            name='incInSpecial',
        ),
        migrations.AlterField(
            model_name='treestand',
            name='avail',
            field=models.BooleanField(default=True),
        ),
    ]
