# Generated by Django 2.0.3 on 2019-12-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191221_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeSkirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('White', 'White'), ('Trees', 'Trees'), ('Bells', 'Bells'), ('Wreaths', 'Wreaths'), ('Bows', 'Bows'), ('Candy Canes', 'Candy Canes'), ('Snowflakes', 'Snowflakes'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=11)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='ribbon',
            name='item',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('White', 'White'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Blue', 'Blue')], max_length=7),
        ),
        migrations.AlterField(
            model_name='tablerunner',
            name='size',
            field=models.CharField(choices=[('4 ft', '4 ft'), ('8 ft', '8 ft'), ('12 ft', '12 ft')], max_length=5),
        ),
    ]
