# Generated by Django 2.0.3 on 2019-12-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191221_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='christmasgreen',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
