# Generated by Django 2.0.3 on 2019-12-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191221_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='treestand',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=5),
            preserve_default=False,
        ),
    ]
