# Generated by Django 2.0.3 on 2019-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_treestand_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bells',
            name='item',
            field=models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('White', 'White'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Clear', 'Clear')], max_length=7),
        ),
    ]
