# Generated by Django 2.0.3 on 2019-12-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191222_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='angel',
            name='avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bells',
            name='avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bow',
            name='avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bulb',
            name='avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lights',
            name='avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ribbon',
            name='avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='star',
            name='avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tablerunner',
            name='avail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='treeskirt',
            name='avail',
            field=models.BooleanField(default=True),
        ),
    ]
