# Generated by Django 2.0.3 on 2019-12-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191222_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('itemId', models.IntegerField()),
                ('orderId', models.IntegerField(default=0)),
                ('itemChoice', models.IntegerField(choices=[(0, 'Tree'), (1, 'Wreath'), (2, 'Garland'), (3, 'Centerpiece'), (4, 'MiniTree'), (5, 'TreeStand'), (6, 'Lights'), (7, 'TreeSkirt'), (8, 'Runner'), (9, 'Ribbon'), (10, 'Angel'), (11, 'Star'), (12, 'Bow'), (13, 'Bells'), (14, 'Bulbs')], default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.IntegerField(choices=[(0, 'Cancelled'), (1, 'Cart'), (2, 'Submitted'), (3, 'In Progress'), (4, 'Assembling'), (5, 'Shipped'), (6, 'Received'), (7, 'Completed')], default=1)),
                ('itemDesc', models.CharField(default=None, max_length=100)),
                ('specialInstructions', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('itemId', models.IntegerField()),
                ('orderId', models.IntegerField(default=0)),
                ('itemChoice', models.IntegerField(choices=[(0, 'Tree'), (1, 'Wreath'), (2, 'Garland'), (3, 'Centerpiece'), (4, 'MiniTree'), (5, 'TreeStand'), (6, 'Lights'), (7, 'TreeSkirt'), (8, 'Runner'), (9, 'Ribbon'), (10, 'Angel'), (11, 'Star'), (12, 'Bow'), (13, 'Bells'), (14, 'Bulbs')], default=0)),
                ('rating', models.CharField(choices=[('*', 'Really did not like'), ('**', 'Did not like'), ('***', 'Liked'), ('****', 'Loved'), ('*****', 'Really Loved')], max_length=20)),
                ('comment', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
